version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis-auth
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379 --requirepass ${redis_password:-change}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge
volumes:
  redis_data:
    driver: local