version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis-chat-db
    command: redis-server --requirepass ${redis_password:-change}
    ports:
      - "6379:6379"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge