version: '3'
services:
#  redis:
#    image: redis:alpine
#    container_name: redis-chat-db
#    command: redis-server --requirepass ${redis_password:-change}
#    ports:
#      - "6379:6379"
#    networks:
#      - local_network
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - local_network
    restart: always
networks:
  local_network:
    driver: bridge