apiVersion: v1
kind: Service
metadata:
  name: boauth
  labels:
    app: boauth
spec:
  type: ClusterIP   # или NodePort/LoadBalancer, если нужен доступ извне
  selector:
    app: boauth
  ports:
    - name: http
      port: 80       # порт сервиса
      targetPort: 8123 # порт контейнера
